// Static typed knowledge base for KC Import and Export Private Limited
// Used by RAG retrieval to provide grounded, verified context to the AI Sales Assistant

import { KnowledgeChunk } from "./ai-types";

export const KC_KNOWLEDGE_BASE: KnowledgeChunk[] = [
  // ==========================================
  // 1. COMPANY OVERVIEW (2 chunks)
  // ==========================================
  {
    id: "kc-comp-overview",
    type: "company",
    title: "About KC Import and Export Private Limited",
    content:
      "KC Import and Export Private Limited is a premier Indian government-recognized export trading corporation headquartered in Rajkot, Gujarat, India (IEC Code: 0823901928, GSTIN: 24AABCK1234F1Z5). Founded to bridge western Indian manufacturing prowess and Saurashtra agricultural richness with international buyers, KC specializes in 6 core categories: Agricultural Commodities, Precision Brass Components, Industrial Hardware, Textiles & Yarns, Processed Food Products, and Ceramic & Vitrified Tiles.",
    keywords: [
      "company",
      "about",
      "location",
      "rajkot",
      "gujarat",
      "india",
      "iec",
      "gstin",
      "who is kc",
      "exporter",
      "manufacturer",
    ],
  },
  {
    id: "kc-comp-logistics",
    type: "company",
    title: "Port Logistics, Infrastructure & Facilities",
    content:
      "Operating from our 25,000 sq.ft. modern export warehousing and staging facility in GIDC Industrial Estate, Rajkot, Gujarat, KC is strategically positioned within 200–350 km of India's two leading deep-water container ports: Mundra Port and Pipavav Port, plus Kandla Port for bulk dry cargo. We maintain dedicated temperature-controlled zones for agro-commodities, precision gauging bays for machined parts, and direct container stuffing docks capable of handling 20+ FCL containers simultaneously.",
    keywords: [
      "port",
      "mundra",
      "pipavav",
      "kandla",
      "logistics",
      "warehouse",
      "facility",
      "gidc",
      "rajkot",
      "stuffing",
      "fcl",
      "shipping",
    ],
  },

  // ==========================================
  // 2. PRODUCT CATALOG (12 chunks, 1 per product)
  // ==========================================
  {
    id: "kc-prod-cumin",
    type: "product",
    productId: "prod-cumin-seeds",
    title: "Premium Whole Cumin Seeds (Jeera) — Export Grade",
    content:
      "Product: Premium Whole Cumin Seeds (Jeera). SKU: AGR-CUM-001. HS Code: 09093129. Origin: Saurashtra & Unjha, Gujarat, India. Grade: Singapore Quality (99% purity) and Europe Quality (99.5% Sortex Cleaned). Specifications: Moisture Max 8.5%, Volatile Oil Min 2.5%-3.0%, Total Ash Max 8.0%, Acid Insoluble Ash Max 1.0%, Salmonella Absent in 25g. Packaging: 25kg / 50kg multi-layer Kraft paper bags, PP bags with inner polythene liner, or 1 MT bulk jumbo totes. MOQ: 1 Metric Ton (LCL trial) or 13.5 MT (20ft FCL container). Custom branding available on bags.",
    keywords: [
      "cumin",
      "jeera",
      "spices",
      "seeds",
      "AGR-CUM-001",
      "09093129",
      "sortex",
      "volatile oil",
      "singapore quality",
      "europe quality",
      "purity",
    ],
  },
  {
    id: "kc-prod-turmeric",
    type: "product",
    productId: "prod-turmeric-fingers",
    title: "Certified Whole Dry Turmeric Fingers — High Curcumin",
    content:
      "Product: Certified Whole Dry Turmeric Fingers (Salem / Nizamabad / Erode). SKU: AGR-TUR-002. HS Code: 09103020. Origin: India. Specifications: Active Curcumin Content 3.5% to 5.0%, Moisture Max 10.0%, Total Ash Max 7.0%, Double polished, free from lead chromate, Sudan dye, and artificial coloring. Packaging: 25kg / 50kg new jute bags or food-grade woven PP bags. MOQ: 2 Metric Tons (LCL) or 18 MT (20ft FCL). Applications: Food processing, spice grinding, dietary supplements, extraction.",
    keywords: [
      "turmeric",
      "curcumin",
      "haldi",
      "fingers",
      "AGR-TUR-002",
      "09103020",
      "salem",
      "nizamabad",
      "polished",
      "spice",
    ],
  },
  {
    id: "kc-prod-brass-inserts",
    type: "product",
    productId: "prod-brass-inserts",
    title: "Precision CNC Brass Threaded Inserts & Turned Parts",
    content:
      "Product: Precision CNC Brass Threaded Inserts & Turned Custom Parts. SKU: IND-BRS-003. HS Code: 74153390. Material: Free Cutting Brass IS 319 Type (I) / CW614N / CZ121 / CuZn39Pb3, Lead-Free Brass options available. Specifications: Thread sizes M2 to M16, UNC/UNF/BSW threads, tolerance down to ±0.01 mm, knurling styles diamond, straight, helical, unidirectional. RoHS and REACH compliant. Packaging: 500 to 2,000 pcs per moisture-proof poly bag, heavy corrugated cartons, wooden euro pallets. MOQ: 10,000 Pieces. Custom manufacturing according to 2D/3D CAD drawings.",
    keywords: [
      "brass",
      "inserts",
      "threaded",
      "cnc",
      "turned parts",
      "knurling",
      "IND-BRS-003",
      "74153390",
      "cw614n",
      "rohs",
      "reach",
      "jamnagar",
    ],
  },
  {
    id: "kc-prod-flanges",
    type: "product",
    productId: "prod-flanges-bushings",
    title: "Forged Stainless Steel Pipe Flanges & Bushings",
    content:
      "Product: Forged Stainless Steel Pipe Flanges & Heavy Bushings. SKU: IND-FLG-004. HS Code: 73072100. Material: ASTM A182 F304, F304L, F316, F316L, Carbon Steel ASTM A105. Pressure Ratings: Class 150 to Class 2500, PN6 to PN100. Types: Weld Neck (WN), Slip-On (SO), Blind (BL), Socket Weld (SW), Lap Joint. Standards: ASME B16.5, EN 1092-1, DIN, BS, JIS. Complete with EN 10204 3.1 Mill Test Certificates. Packaging: Anti-rust oiled, seaworthy fumigated wooden boxes. MOQ: 50 Pieces.",
    keywords: [
      "flanges",
      "stainless steel",
      "bushings",
      "astm a182",
      "f304",
      "f316",
      "asme b16.5",
      "weld neck",
      "slip on",
      "IND-FLG-004",
      "73072100",
      "piping",
    ],
  },
  {
    id: "kc-prod-cotton-yarn",
    type: "product",
    productId: "prod-cotton-yarn",
    title: "Pure Combed Cotton Ring-Spun Yarn (Ne 30s & Ne 40s)",
    content:
      "Product: 100% Pure Combed Cotton Ring-Spun Yarn. SKU: TEX-YRN-005. HS Code: 52052300. Raw Cotton Source: Shankar-6 Gujarat Premium Cotton. Counts: Ne 30/1, Ne 40/1, Ne 30/2, Ne 40/2 (knitting and weaving twist). Quality: Uster top 5% statistics, CSP 2800+, low IPI imperfections, auto-coned and electronically cleared. Packaging: Paper cones of 1.89 kg, 24 cones per export carton box (45.36 kg net) or palletized. MOQ: 5 Metric Tons (or 1x 40ft HQ container of ~20 MT). Certifications: OEKO-TEX Standard 100, BCI Cotton.",
    keywords: [
      "cotton",
      "yarn",
      "ring-spun",
      "combed",
      "ne 30s",
      "ne 40s",
      "shankar-6",
      "textiles",
      "TEX-YRN-005",
      "52052300",
      "oeko-tex",
    ],
  },
  {
    id: "kc-prod-woven-fabrics",
    type: "product",
    productId: "prod-woven-fabrics",
    title: "Organic Raw Cotton Woven Grey Fabrics (Greige)",
    content:
      "Product: Organic Raw Cotton Woven Grey Fabrics (Greige Cloth). SKU: TEX-FAB-006. HS Code: 52081190. Construction: Plain, Twill, Satin, Canvas weaves from 100 to 350 GSM. Looms: High-speed Airjet and Sulzer projectile looms with clean selvedge. Width: 48 inches up to 130 inches wide. Certifications: GOTS (Global Organic Textile Standard), OEKO-TEX 100. Packaging: 500-1000 meter rolls wrapped in moisture-proof HDPE poly sleeves. MOQ: 5,000 Linear Meters. Used for garment dyeing, industrial linens, home furnishings.",
    keywords: [
      "fabrics",
      "greige",
      "grey cloth",
      "woven",
      "organic cotton",
      "gots",
      "airjet",
      "textiles",
      "TEX-FAB-006",
      "52081190",
      "canvas",
    ],
  },
  {
    id: "kc-prod-onion-flakes",
    type: "product",
    productId: "prod-dehydrated-onion",
    title: "Dehydrated White & Red Onion Flakes / Minced",
    content:
      "Product: Dehydrated White & Red Onion (Flakes, Kibbled, Minced, Powder). SKU: FOD-ONN-007. HS Code: 07122000. Origin: Mahuva & Bhavnagar, Gujarat, India. Specifications: Moisture Max 5.0%, Total Ash Max 4.0%, Acid Insoluble Ash Max 0.5%, Micro: TPC <50,000 CFU/g, E. Coli & Salmonella Negative. Free from skin, roots, and foreign matter. Packaging: 20kg poly-lined double Kraft paper bags or corrugated export cartons. MOQ: 1 Metric Ton (or 1x 20ft FCL container ~8 MT). Certifications: BRCGS Food Safety, USFDA, Kosher, Halal.",
    keywords: [
      "onion",
      "dehydrated",
      "flakes",
      "kibbled",
      "powder",
      "mahuva",
      "FOD-ONN-007",
      "07122000",
      "brc",
      "usfda",
      "food processing",
    ],
  },
  {
    id: "kc-prod-mango-pulp",
    type: "product",
    productId: "prod-mango-pulp",
    title: "Premium Alphonso & Kesar Mango Pulp (Aseptic Canned)",
    content:
      "Product: Premium Alphonso & Kesar Mango Pulp / Puree. SKU: FOD-MNG-008. HS Code: 20079910. Variety: Ratnagiri/Devgad Alphonso and Junagadh/Gir Kesar mangoes. Specifications: Min 16° Brix for Alphonso, Min 18° Brix for Kesar, Acidity 0.5% - 0.8%, pH 3.8 - 4.2. Completely aseptic, thermally processed, zero added sugar or artificial preservatives. Packaging: 3.1kg OTS Food Grade Sanitary Cans (6 cans per master carton) or 215kg aseptic bag-in-drum (80 drums per 20ft container). MOQ: 1x 20ft Container (approx 17.2 MT). Certifications: FSSAI, USFDA, ISO 22000, HACCP.",
    keywords: [
      "mango",
      "pulp",
      "puree",
      "alphonso",
      "kesar",
      "aseptic",
      "canned",
      "brix",
      "FOD-MNG-008",
      "20079910",
      "haccp",
      "gir",
    ],
  },
  {
    id: "kc-prod-lever-handles",
    type: "product",
    productId: "prod-lever-handles",
    title: "Architectural Stainless Steel 304 Lever Door Handles",
    content:
      "Product: Architectural Stainless Steel 304 Solid Lever Door Handles. SKU: HRD-HND-009. HS Code: 83024110. Material: Solid Investment Cast Stainless Steel AISI 304 / AISI 316. Finishes: Satin Brushed Nickel (US32D), Mirror Polish, Matte Black PVD, Antique Brass PVD. Standards: Tested to EN 1906 Grade 4 (over 200,000 cycles), Salt Spray resistance >240 hours. Includes 8mm spindle, through-bolts, and hex key. Packaging: Custom foam-padded gift box per pair, 20 pairs per master carton. MOQ: 200 Pairs. OEM laser marking and custom packaging available.",
    keywords: [
      "door handles",
      "lever",
      "hardware",
      "stainless steel 304",
      "en 1906",
      "pvd",
      "satin",
      "HRD-HND-009",
      "83024110",
      "architectural",
    ],
  },
  {
    id: "kc-prod-spanners",
    type: "product",
    productId: "prod-spanners-tools",
    title: "Drop-Forged Chrome Vanadium Combination Spanners",
    content:
      "Product: Industrial Drop-Forged Chrome Vanadium Combination Spanners & Wrenches. SKU: HRD-TLS-010. HS Code: 82041100. Material: Chrome Vanadium 31CrV3 Alloy Steel. Standards: DIN 3113 Form A / ISO 7738, Hardness 44-50 HRC, Torque exceeds ANSI specifications by 30%. Finishes: Satin Chrome, Full Mirror Polish, Industrial Black Phosphate. Sizes: 6mm to 36mm (metric), 1/4 inch to 1-1/2 inch (imperial). Sets: 6, 8, 12, and 25-piece pouch sets or blow-mold cases. MOQ: 500 Sets. Private label stamping on tool bodies.",
    keywords: [
      "spanners",
      "wrenches",
      "tools",
      "chrome vanadium",
      "din 3113",
      "hand tools",
      "hardware",
      "HRD-TLS-010",
      "82041100",
      "oem",
    ],
  },
  {
    id: "kc-prod-vitrified-tiles",
    type: "product",
    productId: "prod-vitrified-tiles",
    title: "Polished Glazed Vitrified Porcelain Floor Tiles (PGVT/GVT)",
    content:
      "Product: Polished Glazed Vitrified Porcelain Tiles (PGVT / GVT). SKU: CER-TIL-011. HS Code: 69072100. Origin: Morbi Industrial Ceramic Cluster, Gujarat. Dimensions: 600x600 mm, 600x1200 mm, 800x1600 mm, 1200x1800 mm. Thickness: 9mm to 12mm. Water Absorption: Ultra-low <0.05% (ISO 10545-3). Finishes: High Gloss Nano-Polished, Matte Silk, Carving, Sugar, Bookmatch Marble Reproductions. Packaging: Corrugated boxes with edge protectors on heavy fumigated wooden pallets. MOQ: 1x 20ft Container (~1,200 to 1,400 sq.meters).",
    keywords: [
      "tiles",
      "vitrified",
      "porcelain",
      "pgvt",
      "gvt",
      "morbi",
      "flooring",
      "marble",
      "CER-TIL-011",
      "69072100",
      "ceramic",
    ],
  },
  {
    id: "kc-prod-sanitaryware",
    type: "product",
    productId: "prod-sanitaryware",
    title: "Designer Vitreous China Ceramic Sanitaryware Suite",
    content:
      "Product: Luxury Vitreous China Ceramic Sanitaryware Suite (One-Piece Water Closets, Wall-Hung Toilets, Countertop Basins). SKU: CER-SAN-012. HS Code: 69101000. Features: Tornado Rimless Flushing System, Dual-flush eco valves (3L/4.5L), UF Soft-Closing Quick-Release Seat Covers, Self-Cleaning Nano Anti-Bacterial Glaze. Certifications: CE (EN 997), SASO (Saudi Arabia), WaterMark (Australia). Packaging: 5-ply honeycomb carton with high-density EPE foam cushions. MOQ: 100 Pieces (or mixed 20ft container). OEM branding available.",
    keywords: [
      "sanitaryware",
      "toilet",
      "basin",
      "vitreous china",
      "rimless",
      "saso",
      "watermark",
      "ceramic",
      "CER-SAN-012",
      "69101000",
      "bathroom",
    ],
  },

  // ==========================================
  // 3. EXPORT PROCESS STEPS (8 chunks)
  // ==========================================
  {
    id: "kc-step-1-inquiry",
    type: "process",
    title: "Export Process Step 1: Initial RFQ & Technical Requirement",
    content:
      "Step 1 of KC Export Protocol: Buyer submits detailed Request for Quotation (RFQ) specifying product name, grade, technical specifications, required volume, packaging requirements, target delivery date, and port of destination (POD). KC's commercial engineering team reviews feasibility and technical parameters within 24 business hours.",
    keywords: [
      "step 1",
      "process",
      "rfq",
      "inquiry",
      "technical specifications",
      "pod",
      "feasibility",
      "requirement",
    ],
  },
  {
    id: "kc-step-2-quotation",
    type: "process",
    title: "Export Process Step 2: Commercial Quotation & Proforma Invoice",
    content:
      "Step 2 of KC Export Protocol: KC prepares a formal Proforma Invoice (PI) detailing firm unit pricing under chosen Incoterms (FOB Mundra, CIF destination port, or CFR), HS codes, production lead times, payment terms, and container stuffing optimization estimates.",
    keywords: [
      "step 2",
      "quotation",
      "proforma invoice",
      "pi",
      "incoterms",
      "fob",
      "cif",
      "cfr",
      "pricing",
    ],
  },
  {
    id: "kc-step-3-contract",
    type: "process",
    title: "Export Process Step 3: Formal Contract & Payment Instrument",
    content:
      "Step 3 of KC Export Protocol: Mutual signing of the Sales Purchase Agreement (SPA). The buyer establishes agreed financial instrument: Irrevocable Letter of Credit (LC) at sight issued by an international prime bank, or Telegraphic Transfer (TT) advance deposit (typically 30% advance, 70% against Bill of Lading copy).",
    keywords: [
      "step 3",
      "contract",
      "spa",
      "payment",
      "letter of credit",
      "lc",
      "tt",
      "telegraphic transfer",
      "deposit",
    ],
  },
  {
    id: "kc-step-4-qc",
    type: "process",
    title: "Export Process Step 4: Manufacturing & Quality Control Audit",
    content:
      "Step 4 of KC Export Protocol: Production commences under strict ISO 9001 guidelines. For agro-commodities, lot-wise sampling and testing for moisture, purity, and microbiology are performed. For engineered goods, CMM dimensional inspection is executed. Third-party pre-shipment inspections (SGS, Intertek, Bureau Veritas, Cotecna) are welcomed prior to packing.",
    keywords: [
      "step 4",
      "manufacturing",
      "quality control",
      "qc",
      "inspection",
      "sgs",
      "intertek",
      "bureau veritas",
      "audit",
    ],
  },
  {
    id: "kc-step-5-packaging",
    type: "process",
    title: "Export Process Step 5: Export Packaging & Palletization",
    content:
      "Step 5 of KC Export Protocol: Finished products are packed in seaworthy, export-grade packaging (ISPM-15 heat-treated fumigated wooden pallets, multi-layer Kraft bags with silica gel desiccants, corner protection, shrink-wrapping). Custom shipping marks, barcodes, and buyer OEM labels applied as contracted.",
    keywords: [
      "step 5",
      "packaging",
      "palletization",
      "ispm-15",
      "fumigation",
      "shipping marks",
      "labels",
      "seaworthy",
    ],
  },
  {
    id: "kc-step-6-customs",
    type: "process",
    title: "Export Process Step 6: Indian Customs Clearance & Port Stuffing",
    content:
      "Step 6 of KC Export Protocol: Cargo is transported via bonded logistics corridors from Rajkot to Mundra or Pipavav Port. KC's licensed customs clearing agents (CHA) file the export Shipping Bill through ICEGATE, complete factory or dock stuffing, arrange phytosanitary and export inspections, and obtain customs 'Let Export Order' (LEO).",
    keywords: [
      "step 6",
      "customs",
      "clearance",
      "cha",
      "icegate",
      "shipping bill",
      "leo",
      "stuffing",
      "mundra",
      "pipavav",
    ],
  },
  {
    id: "kc-step-7-freight",
    type: "process",
    title: "Export Process Step 7: Ocean / Air Freight Dispatch & Tracking",
    content:
      "Step 7 of KC Export Protocol: Containers are loaded aboard scheduled commercial liner services (Maersk, MSC, CMA CGM, Hapag-Lloyd, ONE). The buyer receives immediate shipping advice with container numbers, vessel name, voyage ID, and live satellite container tracking link.",
    keywords: [
      "step 7",
      "freight",
      "shipping",
      "ocean freight",
      "tracking",
      "vessel",
      "container number",
      "maersk",
      "msc",
    ],
  },
  {
    id: "kc-step-8-delivery",
    type: "process",
    title: "Export Process Step 8: Document Surrender & Cargo Handover",
    content:
      "Step 8 of KC Export Protocol: Upon cargo dispatch and final payment settlement, full original shipping documents (Ocean Bill of Lading, Commercial Invoice, Packing List, Certificate of Origin, Certificate of Analysis, Phytosanitary Certificate, Marine Insurance Policy) are surrendered electronically (Telex Release / Sea Waybill) or dispatched via international express courier (DHL / FedEx) for seamless destination clearance.",
    keywords: [
      "step 8",
      "documents",
      "bill of lading",
      "bl",
      "telex release",
      "surrender",
      "dhl",
      "clearance",
      "certificate of origin",
    ],
  },

  // ==========================================
  // 4. TRADE FAQS (5 chunks)
  // ==========================================
  {
    id: "kc-faq-payment-terms",
    type: "faq",
    title: "What are KC's accepted payment terms?",
    content:
      "We offer two primary international trade payment options: 1) Irrevocable Letter of Credit (L/C at sight), 100% confirmed by a prime first-class international bank; 2) Telegraphic Transfer (T/T), structured as 30% advance deposit upon Proforma Invoice confirmation, and balance 70% payable immediately upon email transmission of original draft Bill of Lading (B/L) and shipping documents. For established long-term repeat buyers, we also consider DA/DP terms through credit insurance (ECGC).",
    keywords: [
      "payment terms",
      "lc",
      "letter of credit",
      "tt",
      "advance",
      "deposit",
      "balance",
      "ecgc",
      "how to pay",
      "credit",
    ],
  },
  {
    id: "kc-faq-sampling",
    type: "faq",
    title: "Does KC provide product samples prior to bulk orders?",
    content:
      "Yes, we provide complimentary quality verification samples for almost all product lines (e.g., up to 500g of agricultural commodities, whole spices, or 2 to 5 pieces of brass inserts and fasteners). While sample materials are free of charge, the international express courier charges (DHL / FedEx / Aramex) must be covered by the buyer or charged to their corporate courier account. Courier fees are 100% reimbursed against the first commercial production order.",
    keywords: [
      "samples",
      "sampling",
      "free sample",
      "courier",
      "dhl",
      "fedex",
      "trial",
      "test",
      "prototype",
    ],
  },
  {
    id: "kc-faq-lead-time",
    type: "faq",
    title: "What is the typical production and delivery lead time?",
    content:
      "Lead times depend on the product category: Ready agricultural commodities (cumin, turmeric) can be Sortex cleaned, packaged, and container-stuffed within 10 to 15 calendar days from order confirmation. Engineered brass components, stainless steel flanges, and hardware require 20 to 30 days for CNC tooling, production, and QC audits. Custom porcelain tile batches or ceramic suites typically require 25 to 35 days. Transit time via ocean freight from Mundra Port: 3–5 days to UAE/Gulf, 18–25 days to Western Europe, 28–35 days to US East Coast.",
    keywords: [
      "lead time",
      "delivery time",
      "how long",
      "production time",
      "transit time",
      "shipping days",
      "eta",
    ],
  },
  {
    id: "kc-faq-moq",
    type: "faq",
    title: "What are the Minimum Order Quantities (MOQ)?",
    content:
      "To optimize ocean freight costs, we generally recommend Full Container Loads (FCL). However, we accommodate LCL (Less than Container Load) orders for evaluation. General MOQs: Agricultural Spices (Cumin, Turmeric) = 1 Metric Ton (LCL) or 14 MT (20ft FCL); Brass Turned Inserts = 10,000 pieces; Stainless Flanges = 50 pieces; Cotton Yarn = 5 MT; Dehydrated Onion = 1 MT; Architectural Handles = 200 pairs; Vitrified Tiles = 1x 20ft container (~1,200 sq.meters).",
    keywords: [
      "moq",
      "minimum order quantity",
      "minimum order",
      "small order",
      "trial order",
      "lcl",
      "fcl",
      "container load",
    ],
  },
  {
    id: "kc-faq-private-label",
    type: "faq",
    title: "Does KC support OEM private labeling and custom packaging?",
    content:
      "Yes, full OEM private labeling is available across all 6 product categories. We can print your company logo, trade brand, barcode, batch numbers, and origin compliance markings on individual consumer packaging (foil pouches, printed cartons, tin cans), master outer cartons, and pallet wrap. Custom engineering according to proprietary technical drawings and CAD files is standard practice for our brass and machining division.",
    keywords: [
      "private label",
      "oem",
      "branding",
      "custom packaging",
      "custom logo",
      "white label",
      "customization",
    ],
  },

  // ==========================================
  // 5. GLOBAL MARKETS SERVED (3 chunks)
  // ==========================================
  {
    id: "kc-market-americas",
    type: "market",
    title: "Export Markets: United States & North America",
    content:
      "KC regularly exports to the United States and Canada. All food and agricultural exports are fully registered with USFDA regulations, and engineered brass/steel components comply with ASTM and ASME standards. Transit time from Mundra Port to New York / Savannah / Houston is approximately 28 to 35 days.",
    keywords: [
      "usa",
      "united states",
      "america",
      "canada",
      "usfda",
      "astm",
      "asme",
      "north america",
      "houston",
      "new york",
    ],
  },
  {
    id: "kc-market-middle-east",
    type: "market",
    title: "Export Markets: United Arab Emirates, Saudi Arabia & GCC",
    content:
      "The Gulf Cooperation Council (GCC) represents one of KC's largest trade corridors. We ship weekly to Jebel Ali (Dubai, UAE), Dammam & Jeddah (Saudi Arabia), Hamad Port (Qatar), and Sohar (Oman). Food shipments are 100% Halal certified, and ceramic/sanitary items conform to SASO standards. Transit time from Mundra/Pipavav is only 3 to 6 days.",
    keywords: [
      "uae",
      "dubai",
      "jebel ali",
      "saudi arabia",
      "gcc",
      "middle east",
      "saso",
      "halal",
      "dammam",
      "jeddah",
    ],
  },
  {
    id: "kc-market-europe-apac",
    type: "market",
    title: "Export Markets: European Union, United Kingdom & Asia-Pacific",
    content:
      "We serve industrial buyers in Germany, France, the United Kingdom, Netherlands, Japan, and Australia. Our agricultural goods comply with strict EU pesticide MRL thresholds and Aflatoxin tests. Industrial hardware and brass items comply with CE marking, RoHS, and REACH directives. Sanitaryware holds WaterMark and CE certification.",
    keywords: [
      "europe",
      "germany",
      "uk",
      "united kingdom",
      "france",
      "japan",
      "australia",
      "rohs",
      "reach",
      "ce",
      "watermark",
      "eu",
    ],
  },

  // ==========================================
  // 6. CERTIFICATIONS & QUALITY ASSURANCE (2 chunks)
  // ==========================================
  {
    id: "kc-cert-agro",
    type: "certification",
    title: "Agricultural & Food Safety Certifications",
    content:
      "KC holds official export registrations and certifications from: APEDA (Agricultural and Processed Food Products Export Development Authority of India), Spices Board of India, FSSAI (Food Safety and Standards Authority of India), USFDA, BRCGS Food Safety, Halal India, and Kosher. Every agro shipment is tested by NABL-accredited laboratories for moisture, purity, microbial load, pesticide residue, and heavy metals.",
    keywords: [
      "apeda",
      "spices board",
      "fssai",
      "usfda",
      "brc",
      "halal",
      "kosher",
      "nabl",
      "pesticide",
      "food safety",
      "certifications",
    ],
  },
  {
    id: "kc-cert-industrial",
    type: "certification",
    title: "Industrial, Engineering & Quality Management Certifications",
    content:
      "Our manufacturing partners and export consolidation facilities operate under ISO 9001:2015 Quality Management Systems. Brass and stainless components hold RoHS and REACH compliance certificates. Flanges are backed by EN 10204 3.1 Mill Test Reports. Ceramic and sanitary suites hold CE (EN 997), SASO, and ISO 10545 test reports. Third-party inspections by SGS, Intertek, or Bureau Veritas are welcomed.",
    keywords: [
      "iso 9001",
      "rohs",
      "reach",
      "mill test certificate",
      "3.1",
      "sgs",
      "intertek",
      "bureau veritas",
      "ce",
      "saso",
      "quality management",
    ],
  },
];
