// Mock Leads Dataset for KC Import and Export Private Limited
// TODO: replace with real API
import { Lead } from "./admin-types";

export const MOCK_LEADS: Lead[] = [
  {
    id: "LEAD-101",
    name: "Johnathan Davis",
    company: "Davis Global Procurement LLC",
    email: "j.davis@davisglobal.com",
    phone: "+1 (555) 234-8901",
    country: "United States",
    productInterest: "Precision CNC Brass Inserts & Turned Components",
    quantity: "50,000 Pieces",
    destination: "Port of Houston",
    status: "new",
    intent: "high",
    notes: "Requires RoHS compliance certificate and sample dispatch via DHL. First time buyer from USA automotive sector.",
    createdAt: "2026-09-14 09:30 AM",
    source: "rfq_form",
  },
  {
    id: "LEAD-102",
    name: "Tariq Al-Mansoor",
    company: "Al-Mansoor Trading & Contracting",
    email: "tariq@almansoor-trade.ae",
    phone: "+971 50 891 2345",
    country: "United Arab Emirates",
    productInterest: "Polished Glazed Vitrified Porcelain Tiles (Morbi Hub)",
    quantity: "3x 20ft Containers",
    destination: "Jebel Ali Port, Dubai",
    status: "negotiation",
    intent: "high",
    notes: "Client requested 4% discount on 600x1200mm tiles for high-rise commercial development in Sharjah. Awaiting CIF freight quote.",
    createdAt: "2026-09-13 04:15 PM",
    source: "whatsapp",
  },
  {
    id: "LEAD-103",
    name: "Klaus Schmidt",
    company: "Schmidt Agrarprodukte GmbH",
    email: "klaus.schmidt@schmidt-agrar.de",
    phone: "+49 30 7891 2340",
    country: "Germany",
    productInterest: "Premium Whole Cumin Seeds (Jeera) — Export Grade",
    quantity: "2x 20ft FCL (26 Metric Tons)",
    destination: "Port of Hamburg",
    status: "quotation_sent",
    intent: "high",
    notes: "Strict requirement for steam-sterilized 99.5% purity cumin. SGS pre-shipment inspection will be required before loading.",
    createdAt: "2026-09-12 11:20 AM",
    source: "rfq_form",
  },
  {
    id: "LEAD-104",
    name: "Sophie Laurent",
    company: "EuroTex Distribution SAS",
    email: "slaurent@eurotex-france.fr",
    phone: "+33 1 45 67 89 10",
    country: "France",
    productInterest: "Organic Raw Cotton Woven Grey Fabrics",
    quantity: "15,000 Linear Meters",
    destination: "Port of Le Havre",
    status: "requirement_confirmed",
    intent: "medium",
    notes: "GOTS organic transaction certificate needed. Swatch samples sent via courier last week, awaiting lab wash report approval.",
    createdAt: "2026-09-11 02:45 PM",
    source: "ai_chat",
  },
  {
    id: "LEAD-105",
    name: "Liam O'Connor",
    company: "Oceanic Hardware Supplies Pty",
    email: "liam@oceanichardware.com.au",
    phone: "+61 2 9876 5432",
    country: "Australia",
    productInterest: "Architectural Stainless Steel 304 Lever Handles",
    quantity: "1,200 Pairs",
    destination: "Port of Sydney",
    status: "contacted",
    intent: "medium",
    notes: "Inquired about custom matte black PVD coating and laser engraved branding on rosette. Sales rep scheduled Zoom meeting.",
    createdAt: "2026-09-10 08:10 AM",
    source: "direct",
  },
  {
    id: "LEAD-106",
    name: "Ahmed Hassan",
    company: "Nile Valley Agro Processing Ltd",
    email: "ahmed.hassan@nilevalley.eg",
    phone: "+20 2 2456 7890",
    country: "Egypt",
    productInterest: "Dehydrated White & Red Onion Flakes / Granules",
    quantity: "1x 40ft FCL (15 Metric Tons)",
    destination: "Port of Alexandria",
    status: "won",
    intent: "high",
    notes: "PO confirmed! LC at sight received from National Bank of Egypt. Factory in Mahuva commenced batch production.",
    createdAt: "2026-09-08 10:00 AM",
    source: "rfq_form",
  },
  {
    id: "LEAD-107",
    name: "Kenji Sato",
    company: "Tokyo Precision Machining Corp",
    email: "sato.k@tokyomachining.jp",
    phone: "+81 3 5555 0192",
    country: "Japan",
    productInterest: "Forged Stainless Steel Pipe Flanges & Bushings",
    quantity: "800 Pieces",
    destination: "Port of Yokohama",
    status: "negotiation",
    intent: "high",
    notes: "Custom tolerance inspection ±0.005mm. Mill test report 3.1 requested. Target delivery mid-November.",
    createdAt: "2026-09-07 01:15 PM",
    source: "direct",
  },
  {
    id: "LEAD-108",
    name: "Mateo Rossi",
    company: "Milano Ceramiche S.r.l.",
    email: "m.rossi@milanoceramiche.it",
    phone: "+39 02 8765 4321",
    country: "Italy",
    productInterest: "Designer Vitreous China Ceramic Sanitaryware Sets",
    quantity: "1x 40ft HQ Container (450 sets)",
    destination: "Port of Genoa",
    status: "lost",
    intent: "low",
    notes: "Buyer opted for local European supplier due to shorter 2-week lead time constraints for sudden renovation contract.",
    createdAt: "2026-09-05 03:30 PM",
    source: "rfq_form",
  },
  {
    id: "LEAD-109",
    name: "Carlos Gomez",
    company: "Iberica Herramientas Industriales",
    email: "cgomez@ibericatools.es",
    phone: "+34 91 234 5678",
    country: "Spain",
    productInterest: "Drop-Forged Chrome Vanadium Spanners & Hand Tools",
    quantity: "3,000 Sets",
    destination: "Port of Valencia",
    status: "contacted",
    intent: "medium",
    notes: "Requested canvas roll pouch packaging with Spanish technical labeling. Sample kit shipped.",
    createdAt: "2026-09-04 11:50 AM",
    source: "ai_chat",
  },
  {
    id: "LEAD-110",
    name: "David Kim",
    company: "Seoul Food Ingredients Inc",
    email: "david.kim@seoulfooding.kr",
    phone: "+82 2 3456 7891",
    country: "South Korea",
    productInterest: "Premium Alphonso Mango Pulp & Fruit Puree",
    quantity: "80 Steel Drums (17.2 MT)",
    destination: "Port of Busan",
    status: "new",
    intent: "high",
    notes: "Inquiry received this morning. Aseptic packaging specifications match Korean FDA guidelines. Fast response needed.",
    createdAt: "2026-09-03 09:05 AM",
    source: "rfq_form",
  },
];
