// Mock RFQ Dataset for KC Import and Export Private Limited
// TODO: replace with real API
import { RFQ } from "./admin-types";

export const MOCK_RFQS: RFQ[] = [
  {
    id: "RFQ-2026-001",
    leadId: "LEAD-101",
    buyerName: "Johnathan Davis",
    company: "Davis Global Procurement LLC",
    email: "j.davis@davisglobal.com",
    phone: "+1 (555) 234-8901",
    country: "United States",
    product: "Precision CNC Brass Inserts & Turned Components",
    sku: "IND-BRS-003",
    quantity: "50,000 Pieces",
    destination: "Port of Houston",
    deliveryDate: "2026-11-15",
    specifications: "M4 and M6 knurled brass threaded inserts according to DIN 16903. RoHS lead compliance < 4% strictly mandatory. Seaworthy cardboard carton with poly-bag inner liner.",
    targetPrice: "$0.14 / unit CIF Houston",
    hasAttachment: true,
    status: "pending",
    createdAt: "2026-09-14 09:30 AM",
    aiSummary: "High-probability US automotive buyer inquiry. Tight tolerance M4/M6 threaded brass inserts. Recommends standard Rajkot CNC batch run with SGS test report.",
  },
  {
    id: "RFQ-2026-002",
    leadId: "LEAD-102",
    buyerName: "Tariq Al-Mansoor",
    company: "Al-Mansoor Trading & Contracting",
    email: "tariq@almansoor-trade.ae",
    phone: "+971 50 891 2345",
    country: "United Arab Emirates",
    product: "Polished Glazed Vitrified Porcelain Tiles (Morbi Hub)",
    sku: "CER-TIL-011",
    quantity: "3x 20ft Containers (4,140 m²)",
    destination: "Jebel Ali Port, Dubai",
    deliveryDate: "2026-10-30",
    specifications: "600x1200mm Statuario and Carrara marble pattern with nano polish. Right angle rectified edges. Maximum break rate < 0.2%. Wooden palletization with shrink wrap.",
    targetPrice: "$7.20 / m² FOB Mundra",
    hasAttachment: true,
    status: "quoted",
    createdAt: "2026-09-13 04:15 PM",
    aiSummary: "Commercial development in UAE. Quotation sent at $7.45/m² FOB Mundra. Client reviewing container freight options.",
  },
  {
    id: "RFQ-2026-003",
    leadId: "LEAD-103",
    buyerName: "Klaus Schmidt",
    company: "Schmidt Agrarprodukte GmbH",
    email: "klaus.schmidt@schmidt-agrar.de",
    phone: "+49 30 7891 2340",
    country: "Germany",
    product: "Premium Whole Cumin Seeds (Jeera) — Export Grade",
    sku: "AGR-CUM-001",
    quantity: "2x 20ft FCL (26 Metric Tons)",
    destination: "Port of Hamburg",
    deliveryDate: "2026-11-01",
    specifications: "99.5% machine cleaned, steam treated, moisture < 8.0%. Pesticide residue must comply with EU Regulation 396/2005. 25kg multi-wall paper bags.",
    targetPrice: "$3,650 / MT CIF Hamburg",
    hasAttachment: false,
    status: "quoted",
    createdAt: "2026-09-12 11:20 AM",
    aiSummary: "EU compliance critical. Requires accredited lab pesticide screen. Commercial team submitted proposal on September 13.",
  },
  {
    id: "RFQ-2026-004",
    leadId: "LEAD-104",
    buyerName: "Sophie Laurent",
    company: "EuroTex Distribution SAS",
    email: "slaurent@eurotex-france.fr",
    phone: "+33 1 45 67 89 10",
    country: "France",
    product: "Organic Raw Cotton Woven Grey Fabrics",
    sku: "TEX-FAB-006",
    quantity: "15,000 Linear Meters",
    destination: "Port of Le Havre",
    deliveryDate: "2026-12-10",
    specifications: "100% GOTS organic cotton greige fabric, 63 inch width, 180 GSM, plain weave 1x1. Rolls wrapped in heavy polythene with plastic end plugs.",
    targetPrice: "$2.10 / meter FOB Pipavav",
    hasAttachment: true,
    status: "reviewed",
    createdAt: "2026-09-11 02:45 PM",
    aiSummary: "Fabric swatches delivered. Mill booking pending final wash shrinkage test approval from Paris lab.",
  },
  {
    id: "RFQ-2026-005",
    leadId: "LEAD-105",
    buyerName: "Liam O'Connor",
    company: "Oceanic Hardware Supplies Pty",
    email: "liam@oceanichardware.com.au",
    phone: "+61 2 9876 5432",
    country: "Australia",
    product: "Architectural Stainless Steel 304 Lever Handles",
    sku: "HRD-HND-009",
    quantity: "1,200 Pairs",
    destination: "Port of Sydney",
    deliveryDate: "2026-11-20",
    specifications: "AISI 304 grade, PVD Matte Black finish, EN 1906 grade 4 mechanism. Individual customer gift box with barcode labels.",
    targetPrice: "$12.50 / pair FOB Mundra",
    hasAttachment: false,
    status: "reviewed",
    createdAt: "2026-09-10 08:10 AM",
    aiSummary: "Australian standard packaging required. Sample sent to Sydney office for salt spray cycle verification.",
  },
  {
    id: "RFQ-2026-006",
    leadId: "LEAD-106",
    buyerName: "Ahmed Hassan",
    company: "Nile Valley Agro Processing Ltd",
    email: "ahmed.hassan@nilevalley.eg",
    phone: "+20 2 2456 7890",
    country: "Egypt",
    product: "Dehydrated White & Red Onion Flakes / Granules",
    sku: "FOD-ONN-007",
    quantity: "1x 40ft FCL (15 Metric Tons)",
    destination: "Port of Alexandria",
    deliveryDate: "2026-10-15",
    specifications: "14kg poly-lined kraft paper bags. 60% White onion flakes (8-15mm), 40% Red onion minced flakes. Moisture max 4.8%. Halal certificate required.",
    targetPrice: "$2,400 / MT CIF Alexandria",
    hasAttachment: true,
    status: "quoted",
    createdAt: "2026-09-08 10:00 AM",
    aiSummary: "Formal quotation accepted. LC confirmed. Order converted to active won status in production queue.",
  },
  {
    id: "RFQ-2026-007",
    leadId: "LEAD-107",
    buyerName: "Kenji Sato",
    company: "Tokyo Precision Machining Corp",
    email: "sato.k@tokyomachining.jp",
    phone: "+81 3 5555 0192",
    country: "Japan",
    product: "Forged Stainless Steel Pipe Flanges & Bushings",
    sku: "IND-FLG-004",
    quantity: "800 Pieces",
    destination: "Port of Yokohama",
    deliveryDate: "2026-11-28",
    specifications: "ASTM A182 F316L Class 300 Raised Face Slip-On flanges. 100% PMI and ultrasonic inspection. Heavy anti-corrosion coating.",
    targetPrice: "$48.00 / piece FOB Kandla",
    hasAttachment: true,
    status: "pending",
    createdAt: "2026-09-07 01:15 PM",
    aiSummary: "Japanese industrial client. High precision metallurgy. Production team in Rajkot confirming machining schedule.",
  },
  {
    id: "RFQ-2026-008",
    leadId: "LEAD-108",
    buyerName: "Mateo Rossi",
    company: "Milano Ceramiche S.r.l.",
    email: "m.rossi@milanoceramiche.it",
    phone: "+39 02 8765 4321",
    country: "Italy",
    product: "Designer Vitreous China Ceramic Sanitaryware Sets",
    sku: "CER-SAN-012",
    quantity: "1x 40ft HQ Container (450 sets)",
    destination: "Port of Genoa",
    deliveryDate: "2026-10-01",
    specifications: "Rimless Tornado wash down water closets with CE EN 997 certification. Soft close duroplast seat covers.",
    targetPrice: "$65.00 / set FOB Mundra",
    hasAttachment: false,
    status: "archived",
    createdAt: "2026-09-05 03:30 PM",
    aiSummary: "Archived due to buyer's immediate delivery requirement which clashed with 30-day ocean freight schedule.",
  },
  {
    id: "RFQ-2026-009",
    leadId: "LEAD-109",
    buyerName: "Carlos Gomez",
    company: "Iberica Herramientas Industriales",
    email: "cgomez@ibericatools.es",
    phone: "+34 91 234 5678",
    country: "Spain",
    product: "Drop-Forged Chrome Vanadium Spanners & Hand Tools",
    sku: "HRD-TLS-010",
    quantity: "3,000 Sets",
    destination: "Port of Valencia",
    deliveryDate: "2026-12-05",
    specifications: "12-piece combination wrench sets (6-24mm) DIN 3113. Mirror chrome plated with satin handle grip. Custom printed Spanish branding on canvas pouch.",
    targetPrice: "$18.50 / set CIF Valencia",
    hasAttachment: false,
    status: "reviewed",
    createdAt: "2026-09-04 11:50 AM",
    aiSummary: "Technical review complete. Tooling for custom stamping in Rajkot approved. Proforma quotation prepared.",
  },
  {
    id: "RFQ-2026-010",
    leadId: "LEAD-110",
    buyerName: "David Kim",
    company: "Seoul Food Ingredients Inc",
    email: "david.kim@seoulfooding.kr",
    phone: "+82 2 3456 7891",
    country: "South Korea",
    product: "Premium Alphonso Mango Pulp & Fruit Puree",
    sku: "FOD-MNG-008",
    quantity: "80 Steel Drums (17.2 MT)",
    destination: "Port of Busan",
    deliveryDate: "2026-11-10",
    specifications: "Aseptic bag in 215kg drums. 100% pure Alphonso mango with minimum 16° Brix. Certificate of analysis for zero microbiological contamination.",
    targetPrice: "$1,380 / MT CIF Busan",
    hasAttachment: true,
    status: "pending",
    createdAt: "2026-09-03 09:05 AM",
    aiSummary: "High priority fresh inquiry from Seoul. Ready stock available in cold storage staging. Rapid turnaround recommended.",
  },
];
